export const categorias = {
  kata: [
    {
      codigo: 1,
      idadeMin: 0,
      idadeMax: 6,
      categoria: "ABSOLUTO",
      genero: "M",
      faixa: "9° A 6° KYU",
    },
    {
      codigo: 2,
      idadeMin: 0,
      idadeMax: 6,
      categoria: "ABSOLUTO",
      genero: "F",
      faixa: "9° A 6° KYU",
    },
    {
      codigo: 3,
      idadeMin: 7,
      idadeMax: 9,
      categoria: "SUB8/10",
      genero: "M",
      faixa: "9° A 7° KYU",
    },
    {
      codigo: 4,
      idadeMin: 7,
      idadeMax: 9,
      categoria: "SUB8/10",
      genero: "F",
      faixa: "9° A 7° KYU",
    },
    {
      codigo: 5,
      idadeMin: 7,
      idadeMax: 9,
      categoria: "SUB8/10",
      genero: "M",
      faixa: "6° A 4° KYU",
    },
    {
      codigo: 6,
      idadeMin: 7,
      idadeMax: 9,
      categoria: "SUB8/10",
      genero: "F",
      faixa: "6° A 4° KYU",
    },
    {
      codigo: 7,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "M",
      faixa: "9° A 7° KYU",
    },
    {
      codigo: 8,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "F",
      faixa: "9° A 7° KYU",
    },
    {
      codigo: 9,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "M",
      faixa: "6° A 4° KYU",
    },
    {
      codigo: 10,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "F",
      faixa: "6° A 4° KYU",
    },
    {
      codigo: 11,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "M",
      faixa: "3° KYU ACIMA",
    },
    {
      codigo: 12,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "F",
      faixa: "3° KYU ACIMA",
    },
    {
      codigo: 13,
      idadeMin: 13,
      idadeMax: 14,
      categoria: "SUB 14/CADETE",
      genero: "M",
      faixa: "9° A 7° KYU",
    },
    {
      codigo: 14,
      idadeMin: 13,
      idadeMax: 14,
      categoria: "SUB 14/CADETE",
      genero: "F",
      faixa: "9° A 7° KYU",
    },
    {
      codigo: 15,
      idadeMin: 13,
      idadeMax: 14,
      categoria: "SUB 14/CADETE",
      genero: "M",
      faixa: "6° A 4° KYU",
    },
    {
      codigo: 16,
      idadeMin: 13,
      idadeMax: 14,
      categoria: "SUB 14/CADETE",
      genero: "F",
      faixa: "6° A 4° KYU",
    },
    {
      codigo: 17,
      idadeMin: 13,
      idadeMax: 14,
      categoria: "SUB 14/CADETE",
      genero: "M",
      faixa: "3° KYU ACIMA",
    },
    {
      codigo: 18,
      idadeMin: 13,
      idadeMax: 14,
      categoria: "SUB 14/CADETE",
      genero: "F",
      faixa: "3° KYU ACIMA",
    },
    {
      codigo: 19,
      idadeMin: 15,
      idadeMax: 17,
      categoria: "CADETE/JUNIOR",
      genero: "M",
      faixa: "9° A 7° KYU",
    },
    {
      codigo: 20,
      idadeMin: 15,
      idadeMax: 17,
      categoria: "CADETE/JUNIOR",
      genero: "F",
      faixa: "9° A 7° KYU",
    },
    {
      codigo: 21,
      idadeMin: 15,
      idadeMax: 17,
      categoria: "CADETE/JUNIOR",
      genero: "M",
      faixa: "6° A 4° KYU",
    },
    {
      codigo: 22,
      idadeMin: 15,
      idadeMax: 17,
      categoria: "CADETE/JUNIOR",
      genero: "F",
      faixa: "6° A 4° KYU",
    },
    {
      codigo: 23,
      idadeMin: 15,
      idadeMax: 17,
      categoria: "CADETE/JUNIOR",
      genero: "M",
      faixa: "3° KYU ACIMA",
    },
    {
      codigo: 24,
      idadeMin: 15,
      idadeMax: 17,
      categoria: "CADETE/JUNIOR",
      genero: "F",
      faixa: "3° KYU ACIMA",
    },
    {
      codigo: 25,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "9° A 6° KYU",
    },
    {
      codigo: 26,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "9° A 6° KYU",
    },
    {
      codigo: 27,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "5° A 2° KYU",
    },
    {
      codigo: 28,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "5° A 2° KYU",
    },
    {
      codigo: 29,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "1° KYU ACIMA",
    },
    {
      codigo: 30,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "1° KYU ACIMA",
    },
    {
      codigo: 31,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "9° A 6° KYU",
    },
    {
      codigo: 32,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "9° A 6° KYU",
    },
    {
      codigo: 33,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "5° A 2° KYU",
    },
    {
      codigo: 34,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "5° A 2° KYU",
    },
    {
      codigo: 35,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "1° KYU ACIMA",
    },
    {
      codigo: 36,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "1° KYU ACIMA",
    },
    {
      codigo: 37,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "M",
      faixa: "9° A 3° KYU",
    },
    {
      codigo: 38,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "F",
      faixa: "9° A 3° KYU",
    },
    {
      codigo: 39,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "M",
      faixa: "2° KYU ACIMA",
    },
    {
      codigo: 40,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "F",
      faixa: "2° KYU ACIMA",
    },
  ],

  kumite: [
    {
      codigo: 41,
      idadeMin: 0,
      idadeMax: 6,
      categoria: "SUB8",
      genero: "M",
      faixa: "PEGADOR",
      pesoMin: 0,
      pesoMax: 999,
      descricaoPeso: "ABSOLUTO",
    },
    {
      codigo: 42,
      idadeMin: 0,
      idadeMax: 6,
      categoria: "SUB8",
      genero: "F",
      faixa: "PEGADOR",
      pesoMin: 0,
      pesoMax: 999,
      descricaoPeso: "ABSOLUTO",
    },
    {
      codigo: 43,
      idadeMin: 7,
      idadeMax: 9,
      categoria: "SUB8/10",
      genero: "M",
      faixa: "9° A 6° KYU",
      pesoMin: 0,
      pesoMax: 999,
      descricaoPeso: "ABSOLUTO",
    },
    {
      codigo: 44,
      idadeMin: 7,
      idadeMax: 9,
      categoria: "SUB8/10",
      genero: "F",
      faixa: "9° A 6° KYU",
      pesoMin: 0,
      pesoMax: 999,
      descricaoPeso: "ABSOLUTO",
    },
    {
      codigo: 45,
      idadeMin: 7,
      idadeMax: 9,
      categoria: "SUB8/10",
      genero: "M",
      faixa: "5° A 3° KYU",
      pesoMin: 0,
      pesoMax: 35,
      descricaoPeso: "-35Kg",
    },
    {
      codigo: 46,
      idadeMin: 7,
      idadeMax: 9,
      categoria: "SUB8/10",
      genero: "F",
      faixa: "5° A 3° KYU",
      pesoMin: 0,
      pesoMax: 35,
      descricaoPeso: "-35Kg",
    },
    {
      codigo: 47,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "M",
      faixa: "9° A 6° KYU",
      pesoMin: 0,
      pesoMax: 40,
      descricaoPeso: "-40Kg",
    },
    {
      codigo: 48,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "F",
      faixa: "9° A 6° KYU",
      pesoMin: 0,
      pesoMax: 40,
      descricaoPeso: "-40Kg",
    },
    {
      codigo: 49,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "M",
      faixa: "5° A 2° KYU",
      pesoMin: 0,
      pesoMax: 45,
      descricaoPeso: "-45Kg",
    },
    {
      codigo: 50,
      idadeMin: 10,
      idadeMax: 12,
      categoria: "SUB12/14",
      genero: "F",
      faixa: "5° A 2° KYU",
      pesoMin: 0,
      pesoMax: 45,
      descricaoPeso: "-45Kg",
    },
    {
      codigo: 51,
      idadeMin: 13,
      idadeMax: 15,
      categoria: "SUB14/CADETE",
      genero: "M",
      faixa: "9° A 6°KYU",
      pesoMin: 0,
      pesoMax: 45,
      descricaoPeso: "ATE 45Kg",
    },
    {
      codigo: 52,
      idadeMin: 13,
      idadeMax: 15,
      categoria: "SUB14/CADETE",
      genero: "F",
      faixa: "9° A 6° KYU",
      pesoMin: 0,
      pesoMax: 45,
      descricaoPeso: "ATE 45Kg",
    },
    {
      codigo: 53,
      idadeMin: 13,
      idadeMax: 15,
      categoria: "SUB14/CADETE",
      genero: "M",
      faixa: "5° A 2° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 54,
      idadeMin: 13,
      idadeMax: 15,
      categoria: "SUB14/CADETE",
      genero: "F",
      faixa: "5° A 2° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 55,
      idadeMin: 13,
      idadeMax: 15,
      categoria: "SUB14/CADETE",
      genero: "M",
      faixa: "1°KYU ACIMA",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 56,
      idadeMin: 13,
      idadeMax: 15,
      categoria: "SUB14/CADETE",
      genero: "F",
      faixa: "1°KYU ACIMA",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 57,
      idadeMin: 16,
      idadeMax: 17,
      categoria: "JUNIOR",
      genero: "M",
      faixa: "9° A 6° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 58,
      idadeMin: 16,
      idadeMax: 17,
      categoria: "JUNIOR",
      genero: "F",
      faixa: "9° A 6° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 59,
      idadeMin: 16,
      idadeMax: 17,
      categoria: "JUNIOR",
      genero: "M",
      faixa: "5° A 2° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 60,
      idadeMin: 16,
      idadeMax: 17,
      categoria: "JUNIOR",
      genero: "F",
      faixa: "5° A 2° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 61,
      idadeMin: 16,
      idadeMax: 17,
      categoria: "JUNIOR",
      genero: "M",
      faixa: "5° A 2° KYU",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 62,
      idadeMin: 16,
      idadeMax: 17,
      categoria: "JUNIOR",
      genero: "F",
      faixa: "5° A 2° KYU",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 63,
      idadeMin: 16,
      idadeMax: 17,
      categoria: "JUNIOR",
      genero: "M",
      faixa: "1° KYU ACIMA",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 64,
      idadeMin: 16,
      idadeMax: 17,
      categoria: "JUNIOR",
      genero: "F",
      faixa: "1° KYU ACIMA",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 65,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "9° A 5° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 66,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "9° A 5° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 67,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "4° A 2° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 68,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "4° A 2° KYU",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 69,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "4° A 2° KYU",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 70,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "4° A 2° KYU",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 71,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "1° KYU ACIMA",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 72,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "1° KYU ACIMA",
      pesoMin: 0,
      pesoMax: 55,
      descricaoPeso: "ATE 55Kg",
    },
    {
      codigo: 73,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "1° KYU ACIMA",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 74,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "1° KYU ACIMA",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55KgACIMA",
    },
    {
      codigo: 75,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "9° A 5° KYU",
      pesoMin: 0,
      pesoMax: 70,
      descricaoPeso: "ATE 70Kg",
    },
    {
      codigo: 76,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "9° A 5° KYU",
      pesoMin: 0,
      pesoMax: 60,
      descricaoPeso: "ATE 60Kg",
    },
    {
      codigo: 77,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "9° A 5° KYU",
      pesoMin: 70,
      pesoMax: 80,
      descricaoPeso: "70 A 80Kg",
    },
    {
      codigo: 78,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "9° A 5° KYU",
      pesoMin: 60,
      pesoMax: 999,
      descricaoPeso: "60Kg ACIMA",
    },
    {
      codigo: 79,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "4° A 2° KYU",
      pesoMin: 0,
      pesoMax: 70,
      descricaoPeso: "ATE 70Kg",
    },
    {
      codigo: 80,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "4° A 2° KYU",
      pesoMin: 0,
      pesoMax: 60,
      descricaoPeso: "ATE 60Kg",
    },
    {
      codigo: 81,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "4° A 2° KYU",
      pesoMin: 70,
      pesoMax: 80,
      descricaoPeso: "70 A 80Kg",
    },
    {
      codigo: 82,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "4° A 2° KYU",
      pesoMin: 60,
      pesoMax: 999,
      descricaoPeso: "60 Kg ACIMA",
    },
    {
      codigo: 83,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "1° KYU ACIMA",
      pesoMin: 0,
      pesoMax: 70,
      descricaoPeso: "ATE70Kg",
    },
    {
      codigo: 84,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "1° KUI ACIMA",
      pesoMin: 0,
      pesoMax: 60,
      descricaoPeso: "ATE 60Kg",
    },
    {
      codigo: 85,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "M",
      faixa: "1° KYU ACIMA",
      pesoMin: 70,
      pesoMax: 80,
      descricaoPeso: "70 A 80Kg",
    },
    {
      codigo: 86,
      idadeMin: 33,
      idadeMax: 45,
      categoria: "MASTER A",
      genero: "F",
      faixa: "1° KYU ACIMA",
      pesoMin: 60,
      pesoMax: 999,
      descricaoPeso: "60Kg ACIMA",
    },
    {
      codigo: 87,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "M",
      faixa: "9° A 5° KYU",
      pesoMin: 0,
      pesoMax: 80,
      descricaoPeso: "ATE 80Kg",
    },
    {
      codigo: 88,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "F",
      faixa: "9° A 5° KYU",
      pesoMin: 0,
      pesoMax: 80,
      descricaoPeso: "ATE 80Kg",
    },
    {
      codigo: 89,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "M",
      faixa: "9° A 5° KYU",
      pesoMin: 80,
      pesoMax: 999,
      descricaoPeso: "80Kg ACIMA",
    },
    {
      codigo: 90,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "F",
      faixa: "9° A 5° KYU",
      pesoMin: 80,
      pesoMax: 999,
      descricaoPeso: "80Kg ACIMA",
    },
    {
      codigo: 91,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "M",
      faixa: "4° A 2° KYU",
      pesoMin: 0,
      pesoMax: 80,
      descricaoPeso: "ATE 80Kg",
    },
    {
      codigo: 92,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "F",
      faixa: "4° A 2° KYU",
      pesoMin: 0,
      pesoMax: 80,
      descricaoPeso: "ATE 80Kg",
    },
    {
      codigo: 93,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "M",
      faixa: "4° A 2° KYU",
      pesoMin: 80,
      pesoMax: 999,
      descricaoPeso: "80Kg ACIMA",
    },
    {
      codigo: 94,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "F",
      faixa: "4° A 2° KYU",
      pesoMin: 80,
      pesoMax: 999,
      descricaoPeso: "80Kg ACIMA",
    },
    {
      codigo: 95,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "M",
      faixa: "1° KYU ACIMA",
      pesoMin: 0,
      pesoMax: 80,
      descricaoPeso: "ATE 80Kg",
    },
    {
      codigo: 96,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "M",
      faixa: "1° KYU ACIMA",
      pesoMin: 0,
      pesoMax: 80,
      descricaoPeso: "ATE 80Kg",
    },
    {
      codigo: 97,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "F",
      faixa: "1° KUI ACIMA",
      pesoMin: 80,
      pesoMax: 999,
      descricaoPeso: "80Kg ACIMA",
    },
    {
      codigo: 98,
      idadeMin: 46,
      idadeMax: 999,
      categoria: "MASTER B",
      genero: "F",
      faixa: "1° KUI ACIMA",
      pesoMin: 80,
      pesoMax: 999,
      descricaoPeso: "80Kg ACIMA",
    },
    {
      codigo: 99,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "M",
      faixa: "9° A 5° KYU",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 100,
      idadeMin: 18,
      idadeMax: 32,
      categoria: "SENIOR",
      genero: "F",
      faixa: "9° A 5° KYU",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 101,
      idadeMin: 13,
      idadeMax: 32,
      categoria: "SUB14/CADETE",
      genero: "M",
      faixa: "5° A 2° KYU",
      pesoMin: 80,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
    {
      codigo: 102,
      idadeMin: 13,
      idadeMax: 15,
      categoria: "SUB14/CADETE",
      genero: "F",
      faixa: "5° A 2° KYU",
      pesoMin: 55,
      pesoMax: 999,
      descricaoPeso: "55Kg ACIMA",
    },
  ],
};
